# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 16:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(choices=[(1, '小一'), (2, '小二'), (3, '小三'), (4, '小四'), (5, '小五'), (6, '小六'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')], verbose_name='年级')),
                ('subject', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '历史'), (8, '地理'), (9, '政治')], verbose_name='科目')),
                ('plan_time', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 0, 29, 52, 539365), verbose_name='计划时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hours', models.SmallIntegerField(default=2, verbose_name='课时')),
                ('status', models.BooleanField(default=False, verbose_name='完成')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='学生')),
            ],
            options={
                'permissions': (('view_courseplan', 'Can view course plan'),),
            },
        ),
        migrations.CreateModel(
            name='CoursesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.SmallIntegerField(blank=True, choices=[(0, '正常'), (1, '老师缺席'), (2, '学生缺席'), (3, '老师迟到'), (4, '学生迟到'), (5, '老师请假'), (6, '学生请假')], null=True, verbose_name='考勤')),
                ('lesson_time', models.DateTimeField(default=datetime.datetime(2018, 1, 23, 0, 29, 52, 538364), verbose_name='上课时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(choices=[(1, 'finished'), (2, 'deleted'), (3, 'waiting'), (4, 'reschedule')], default=3, verbose_name='状态')),
            ],
            options={
                'permissions': (('view_coursesrecord', 'Can view courses record'),),
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(blank=True, max_length=1024, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/LessonPlan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='teacher_info')),
            ],
            options={
                'permissions': (('view_lessonplan', 'Can view lesson plan'),),
            },
        ),
        migrations.AddField(
            model_name='coursesrecord',
            name='lesson_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.LessonPlan', verbose_name='教案'),
        ),
        migrations.AddField(
            model_name='coursesrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.CoursePlan', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='coursesrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher', verbose_name='教师'),
        ),
    ]
