# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesrecord',
            name='lesson_timedelta',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='plan_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 15, 0), verbose_name='计划时间'),
        ),
        migrations.AlterField(
            model_name='coursesrecord',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 23, 15, 0), verbose_name='上课时间'),
        ),
    ]
