# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180123_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesrecord',
            name='lesson_timedelta',
            field=models.DecimalField(decimal_places=1, default=0.08333333333333333, max_digits=2, verbose_name='上课时长'),
        ),
    ]
