# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180123_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesrecord',
            name='lesson_timedelta',
            field=models.FloatField(default=0.08333333333333333, verbose_name='上课时长'),
        ),
    ]
