# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180123_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='hours',
            field=models.SmallIntegerField(choices=[(1, '一小时'), (2, '二小时'), (3, '三小时'), (4, '四小时')], default=2, verbose_name='课时'),
        ),
    ]
