# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('duty', models.SmallIntegerField(choices=[(0, '教研部'), (1, '班主任'), (2, '专职教师')], default=1, verbose_name='职位')),
                ('branch', models.SmallIntegerField(choices=[(0, '郑州大区'), (1, '郑大校区'), (2, '省实验校区'), (3, '未来路校区'), (4, '洛阳校区'), (5, '碧沙岗校区'), (6, '郑东校区'), (7, '北环校区'), (8, '外国语校区')], default=1, verbose_name='校区')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'permissions': (('view_user', 'Can view user'),),
            },
        ),
    ]
