# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.SmallIntegerField(choices=[(1, '小一'), (2, '小二'), (3, '小三'), (4, '小四'), (5, '小五'), (6, '小六'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
                ('subject', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '历史'), (8, '地理'), (9, '政治')], verbose_name='学科')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.IntegerField(choices=[(3, '优秀'), (2, '普通'), (1, '一般')], verbose_name='水平')),
                ('result', models.IntegerField(choices=[(1, '通过'), (0, '未通过')], verbose_name='结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='面试人')),
                ('grade', models.ManyToManyField(to='main.Grade', verbose_name='年级')),
            ],
            options={
                'permissions': (('view_interview', 'Can view interview'),),
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '父亲'), (0, '母亲')], verbose_name='关系')),
                ('mobile', models.CharField(max_length=32, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '家长信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('branch', models.SmallIntegerField(choices=[(1, '郑大校区'), (2, '省实验校区'), (3, '未来路校区'), (4, '洛阳校区'), (5, '碧沙岗校区'), (6, '郑东校区'), (7, '北环校区'), (8, '外国语校区')], verbose_name='校区')),
                ('grade', models.SmallIntegerField(choices=[(1, '小一'), (2, '小二'), (3, '小三'), (4, '小四'), (5, '小五'), (6, '小六'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三')], verbose_name='年级')),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload/Gravatar/student')),
            ],
            options={
                'verbose_name': '学生信息',
                'permissions': (('view_student', 'Can view student'),),
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')])),
                ('age', models.SmallIntegerField()),
                ('branch', models.SmallIntegerField(choices=[(1, '郑大校区'), (2, '省实验校区'), (3, '未来路校区'), (4, '洛阳校区'), (5, '碧沙岗校区'), (6, '郑东校区'), (7, '北环校区'), (8, '外国语校区')], verbose_name='校区')),
                ('mobile', models.CharField(max_length=32)),
            ],
            options={
                'permissions': (('view_supervisor', 'Can view supervisor'),),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
            ],
            options={
                'permissions': (('view_tag', 'Can view tag'),),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(verbose_name='年龄')),
                ('branch', models.SmallIntegerField(choices=[(1, '郑大校区'), (2, '省实验校区'), (3, '未来路校区'), (4, '洛阳校区'), (5, '碧沙岗校区'), (6, '郑东校区'), (7, '北环校区'), (8, '外国语校区')], verbose_name='校区')),
                ('work_type', models.IntegerField(choices=[(1, '专职'), (0, '兼职')], verbose_name='类别')),
                ('subject', models.SmallIntegerField(choices=[(1, '语文'), (2, '数学'), (3, '英语'), (4, '物理'), (5, '化学'), (6, '生物'), (7, '历史'), (8, '地理'), (9, '政治')], verbose_name='学科')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('grades', models.ManyToManyField(to='main.Grade', verbose_name='辅导年级')),
            ],
            options={
                'permissions': (('view_teacher', 'Can view teacher'),),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Supervisor', verbose_name='班主任'),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='main.Teacher', verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='main.Student'),
        ),
    ]
