# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='plan_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 20, 44, 19, 627614), verbose_name='计划时间'),
        ),
        migrations.AlterField(
            model_name='coursesrecord',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 20, 44, 19, 626614), verbose_name='上课时间'),
        ),
    ]
