# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-18 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180118_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseplan',
            name='plan_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 22, 14, 23, 761081), verbose_name='计划时间'),
        ),
        migrations.AlterField(
            model_name='coursesrecord',
            name='lesson_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 22, 14, 23, 760080), verbose_name='上课时间'),
        ),
    ]
